[colors]
ansi = [
    '#f2f2f2',
    '#c82829',
    '#718c00',
    '#eab700',
    '#4271ae',
    '#8959a8',
    '#60a79d',
    '#000000',
]

brights = [
    '#8e908c',
    '#d55d5e',
    '#94a83f',
    '#efc93f',
    '#81a2be',
    '#d499e5',
    '#8abeb7',
    '#3f3f3f',
]

background = '#ffffff'
foreground = '#3f3f3f'

cursor_bg = '#81a2be'
cursor_border = '#81a2be'
cursor_fg = '#3f3f3f'

selection_bg = '#d6d6d6'
selection_fg = '#4d4d4c'

[colors.indexed]

[metadata]
name = 'tomorrow-day'
